import { readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
// Only the public, static frontend is cached. Never cache API or account responses.
const root = new URL('../dist/', import.meta.url);
const files = (await readdir(root, { recursive: true })).filter(path => /\.(?:html|js|css|svg|png|webmanifest)$/.test(path) && path !== 'sw.js').sort();
const hash = createHash('sha256');
for (const file of files) hash.update(await readFile(new URL(file, root)));
const version = hash.digest('hex').slice(0, 16);
const urls = files.map(file => '/' + file.split('\\').join('/'));
await writeFile(new URL('sw.js', root), `/* ProductPulse static offline shell. Generated by scripts/build-pwa.mjs. */
const CACHE = 'productpulse-shell-${version}';
const FILES = ${JSON.stringify(urls)};
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(FILES)));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith('productpulse-shell-') && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;
  const navigation = request.mode === 'navigate' && (url.pathname === '/' || url.pathname === '/app' || url.pathname.startsWith('/app/') || ['/help','/privacy','/terms','/legal'].includes(url.pathname));
  if (navigation) {
    event.respondWith(fetch(request).catch(() => caches.open(CACHE).then(cache => cache.match('/index.html')).then(response => response || Response.error())));
  } else if (FILES.includes(url.pathname)) {
    event.respondWith(caches.open(CACHE).then(cache => cache.match(url.pathname)).then(response => response || fetch(request)));
  }
});
`);
console.log(`PWA: precached ${urls.length} static files (${version})`);
